### PR TITLE
[NEW PROVIDER] Support to build stemcell on Alibaba Cloud

### PR DESCRIPTION
**Pull request by xiaozhu36**
This PR can help user to build bosh heavy stemcell (ubuntu) on Alibaba Cloud.

At present, for some alicloud ECS design reason, alicloud bosh agent must build all alone, and it is stored in alicloud OSS, and we provide download url in bosh_alicloud_go_agent.

We have made some tests for built stemcell and we can deploy bosh successfully based on it.

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Hi - can you explain more about why a custom bosh-agent is required? This repo shouldn't be pulling in dependencies that we don't have control or insight into. Before this can be merged, any customizations should be pull requested to the bosh-agent repository. Can you describe the agent changes a bit more?

Also, it looks like there were several permission changes made to a few files, if you could take a look and revert those permission changes.

**Comment by xiaozhu36** [comment]
Hi @dpb587-pivotal Registry need to get setting.json and get SSHPublicKey when deploying bosh, and it must run twice curl command to get final SSHPublicKey value in alicloud ECS instance, and we need to modify bosh agent code to achieve it. I'm afraid bosh agent will not accept it, so I had not submit thees changes. May be I can have a try.

In addition, I cannot understand you said about "several permission changes...". Could you please give some details? Thanks a lot.

Regards,
He Guimin

**Comment by cppforlife** [comment]
> In addition, I cannot understand you said about "several permission changes...". Could you please give some details? Thanks a lot.

if you click on "files changed" in this pr, it shows changes like this: "Gemfile 100644 → 100755".

**Comment by cppforlife** [comment]
let's also prepare this PR to use the official agent once we pull in the change for SSH keys.

**Comment by xiaozhu36** [comment]
Hi @cppforlife Thanks for your feedback. I will resolve the issue.

**Comment by dpb587-pivotal** [comment]
🔗 [Story #158921302](https://www.pivotaltracker.com/story/show/158921302)

**Comment by cdutra** [comment]
We [squashed the commits](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/b24ba0f8e115d78b2b718ab1735cddf8621cae67) and merged to master.

**Pull request closed without merging**
