### PR TITLE
fix rsyslog crash in case of connection abort

### PR DESCRIPTION
**Pull request by h0nIg**
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/249

### CODE REVIEW

**Comment by ramonskie** [comment]
it seems that $ModLoad is the legacy use of loading a module.
maby we need to revise this whole config file. can yo confirm this?
i can fix this in a later stage but just wanted some confirmation

**Comment by h0nIg** [comment]
@ramonskie adjustment is not required, even ubuntu did not adjust the configuration. On top of that rainerscript and the old syntax will co-exist: https://rainer.gerhards.net/2008/02/introducing-rainerscript-and-some-rsyslog-futures.html

> I hope you find the choice of name acceptable — and the overall direction we are taking a good one. As a side-note please let me assure that rsyslog’s easy and simple sysklogd-like configuration will not go away. Rainerscript will fully support that syntax, as well as all currently existing $-configuration lines.

Just checked the current rsyslog.conf and it uses both old/new syntax:

```
......
#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
......
```

**Review by ramonskie — APPROVED** [review]
LGTM

**Comment by ramonskie** [comment]
does this also not need to be merged in to bionic?

**Comment by h0nIg** [comment]
@ramonskie https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/255

**Review by rkoster — APPROVED** [review]

**Comment by rkoster** [comment]
@h0nIg Thanks!

**Pull request merged**
