### PR TITLE
remove anything related to building softlayer.

### PR DESCRIPTION
**Pull request by ramonskie**
this will remove anything related to softlayer.

the bosh-stemcell/spec/support/stemcell_image.rb had 1 big if condition with testing shellout types.
i tested the part removed and it works as expected

### CODE REVIEW

**Comment by rkoster** [comment]
Softlayer cpi has been archived here: https://github.com/cloudfoundry/community/pull/1023

**Review by benjaminguttmann-avtq — COMMENTED** [review]
Beside comment https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/b8043b56c570cc81e31a6788892a131716638234/bosh-stemcell/spec/support/stemcell_image.rb#L9 which still mentions softlayer it looks good to me

**Review by benjaminguttmann-avtq — APPROVED** [review]
LGTM

**Review by aramprice — DISMISSED** [review]

**Comment by ramonskie** [comment]
needed to force push as i messed up a merge

**Review by aramprice — APPROVED** [review]

**Review by benjaminguttmann-avtq — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Pull request merged**
