### PR TITLE
add dependency on first boot task (rc.local)

### PR DESCRIPTION
**Pull request by MSSedusch**
Fix for #231

### CODE REVIEW

**Comment by jpalermo** [comment]
Thanks for the PR @MSSedusch, is this likely something we should also merge into the jammy branch?

**Comment by MSSedusch** [comment]
I am testing it right now with jammy. Seems like there is more work to do for jammy. Can we already merge this PR for bionic?

**Comment by jpalermo** [comment]
Yeah, sorry for the delay on this, I haven't had a chance to look at PRs recently.

**Review by jpalermo — COMMENTED** [review]
👍 Thanks!

**Pull request merged**
