### PR TITLE
Add EFI support for vsphere stemcell

### PR DESCRIPTION
**Pull request by lnguyen**
This is for vSphere stemcells can to access > 16 GiB GPUs

Booting from an EFI partition is necessary to access and utilize
GPUs with more than 16 GB of memory because UEFI provides the
advanced memory addressing, compatibility, and initialization
capabilities required for such hardware. The older BIOS/MBR
system cannot efficiently handle the requirements of modern
high-capacity GPUs.

### CODE REVIEW

**Review by jpalermo — APPROVED** [review]
👍

**Comment by cunnie** [comment]
I love this commit, but could you please modify the message (which does a great job of explaining what you did, but glosses over _why_ you did it):

> vSphere stemcells can access > 16 GiB GPUs

> booting from an EFI partition is necessary to access and utilize GPUs with more than 16 GB of memory because UEFI provides the advanced memory addressing, compatibility, and initialization capabilities required for such hardware. The older BIOS/MBR system cannot efficiently handle the requirements of modern high-capacity GPUs.

**Review by cunnie — CHANGES_REQUESTED** [review]
Could you please update your commit message? One that explains _why_ this change was necessary.

**Review by cunnie — APPROVED** [review]
Thanks for updating the commit message! Looks good.

**Pull request merged**
